
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 20;
  public static final int MENOS = 3;
  public static final int MENOR = 17;
  public static final int IDENT = 28;
  public static final int ELSE = 23;
  public static final int CP = 12;
  public static final int PYC = 15;
  public static final int OR = 21;
  public static final int IGUAL = 7;
  public static final int WHILE = 24;
  public static final int ALL = 13;
  public static final int MENIG = 19;
  public static final int CLL = 14;
  public static final int IF = 22;
  public static final int AP = 11;
  public static final int DO = 25;
  public static final int MENOSUNARIO = 6;
  public static final int MAYOR = 16;
  public static final int EOF = 0;
  public static final int MULT = 4;
  public static final int EXC = 9;
  public static final int PRINT = 27;
  public static final int error = 1;
  public static final int MAYIG = 18;
  public static final int DIVID = 5;
  public static final int ASIGNA = 8;
  public static final int ENTERO = 29;
  public static final int FOR = 26;
  public static final int MAS = 2;
  public static final int DIF = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "MULT",
  "DIVID",
  "MENOSUNARIO",
  "IGUAL",
  "ASIGNA",
  "EXC",
  "DIF",
  "AP",
  "CP",
  "ALL",
  "CLL",
  "PYC",
  "MAYOR",
  "MENOR",
  "MAYIG",
  "MENIG",
  "AND",
  "OR",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "PRINT",
  "IDENT",
  "ENTERO"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[20]=new String("AND");
		TT[3]=new String("MENOS");
		TT[17]=new String("MENOR");
		TT[28]=new String("IDENT");
		TT[23]=new String("ELSE");
		TT[12]=new String("CP");
		TT[15]=new String("PYC");
		TT[21]=new String("OR");
		TT[7]=new String("IGUAL");
		TT[24]=new String("WHILE");
		TT[13]=new String("ALL");
		TT[19]=new String("MENIG");
		TT[14]=new String("CLL");
		TT[22]=new String("IF");
		TT[11]=new String("AP");
		TT[25]=new String("DO");
		TT[6]=new String("MENOSUNARIO");
		TT[16]=new String("MAYOR");
		TT[0]=new String("EOF");
		TT[4]=new String("MULT");
		TT[9]=new String("EXC");
		TT[27]=new String("PRINT");
		TT[1]=new String("error");
		TT[18]=new String("MAYIG");
		TT[5]=new String("DIVID");
		TT[8]=new String("ASIGNA");
		TT[29]=new String("ENTERO");
		TT[26]=new String("FOR");
		TT[2]=new String("MAS");
		TT[10]=new String("DIF");
	}
public String getTT(int i){return TT[i];}
}

