
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 3;
  public static final int IDENT = 25;
  public static final int CP = 12;
  public static final int PYC = 16;
  public static final int CONJUNTO = 24;
  public static final int CONCATENA = 7;
  public static final int MATRIZ = 22;
  public static final int ALL = 9;
  public static final int TRANSPUESTA = 19;
  public static final int INVERSA = 18;
  public static final int INTERSECCION = 8;
  public static final int CLL = 10;
  public static final int CC = 14;
  public static final int POR = 4;
  public static final int AP = 11;
  public static final int COMA = 15;
  public static final int EOF = 0;
  public static final int VECTOR = 23;
  public static final int SET = 17;
  public static final int DIV = 5;
  public static final int ADJUNTA = 20;
  public static final int AC = 13;
  public static final int NUMERO = 26;
  public static final int PRINT = 21;
  public static final int error = 1;
  public static final int ASIG = 6;
  public static final int MAS = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "ASIG",
  "CONCATENA",
  "INTERSECCION",
  "ALL",
  "CLL",
  "AP",
  "CP",
  "AC",
  "CC",
  "COMA",
  "PYC",
  "SET",
  "INVERSA",
  "TRANSPUESTA",
  "ADJUNTA",
  "PRINT",
  "MATRIZ",
  "VECTOR",
  "CONJUNTO",
  "IDENT",
  "NUMERO"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[3]=new String("MENOS");
		TT[25]=new String("IDENT");
		TT[12]=new String("CP");
		TT[16]=new String("PYC");
		TT[24]=new String("CONJUNTO");
		TT[7]=new String("CONCATENA");
		TT[22]=new String("MATRIZ");
		TT[9]=new String("ALL");
		TT[19]=new String("TRANSPUESTA");
		TT[18]=new String("INVERSA");
		TT[8]=new String("INTERSECCION");
		TT[10]=new String("CLL");
		TT[14]=new String("CC");
		TT[4]=new String("POR");
		TT[11]=new String("AP");
		TT[15]=new String("COMA");
		TT[0]=new String("EOF");
		TT[23]=new String("VECTOR");
		TT[17]=new String("SET");
		TT[5]=new String("DIV");
		TT[20]=new String("ADJUNTA");
		TT[13]=new String("AC");
		TT[26]=new String("NUMERO");
		TT[21]=new String("PRINT");
		TT[1]=new String("error");
		TT[6]=new String("ASIG");
		TT[2]=new String("MAS");
	}
public String getTT(int i){return TT[i];}
}

