
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 3;
  public static final int IDENT = 23;
  public static final int CP = 9;
  public static final int PYC = 15;
  public static final int CONCATENA = 7;
  public static final int MATRIZ = 16;
  public static final int ALL = 10;
  public static final int TRANSPUESTA = 19;
  public static final int INVERSA = 18;
  public static final int CLL = 11;
  public static final int CC = 13;
  public static final int POR = 4;
  public static final int AP = 8;
  public static final int COMA = 14;
  public static final int EOF = 0;
  public static final int VECTOR = 17;
  public static final int DIV = 5;
  public static final int ADJUNTA = 20;
  public static final int AC = 12;
  public static final int NUMERO = 22;
  public static final int PRINT = 21;
  public static final int error = 1;
  public static final int ASIG = 6;
  public static final int MAS = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "ASIG",
  "CONCATENA",
  "AP",
  "CP",
  "ALL",
  "CLL",
  "AC",
  "CC",
  "COMA",
  "PYC",
  "MATRIZ",
  "VECTOR",
  "INVERSA",
  "TRANSPUESTA",
  "ADJUNTA",
  "PRINT",
  "NUMERO",
  "IDENT"
  };
}

